[build]
builder = "nixpacks"

[deploy]
startCommand = "npm run start:all"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "nextjs-app"
port = 3000

[[services]]
name = "collaboration-server"
port = 3002
